apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base

patches:
  - target: 
      kind: Ingress
      name: octopub-ingress-products
    path: octopub-ingress.yaml
  - target:
      kind: Service
      name: octopub-products-deployment
    path: octopub-products-deployment.yaml
  - target:
      kind: Deployment
      name: octopub-products-service
    path: octopub-products-service.yaml

configMapGenerator:
  - name: product-service-env-vars
    behavior: merge
    env: variables.properties

images:
  - name: ghcrfacade-a6awccayfpcpg4cg.eastus-01.azurewebsites.net/octopub-products-microservice
    newName: octopughcrfacade-a6awccayfpcpg4cg.eastus-01.azurewebsites.netssamples/octopub-products-microservice
    newTag: "20251119.519.1"