apiVersion: apps/v1
kind: Deployment
metadata:
  name: octopub-audit-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: auditservice
  template:
    metadata:
      labels:
        component: auditservice
    spec:
      containers:
        - name: auditservice
          image: ghcrfacade-a6awccayfpcpg4cg.eastus-01.azurewebsites.net/octopussolutionsengineering/octopub-audit-microservice:20251117.496.1
          ports:
            - name: http-audit
              containerPort: 10000
          env:
            - name: MIGRATE_AT_START
              value: "true"
            - name: COGNITO_DISABLE_AUTH
              value: "true"